{{- if and (eq .Values.database.type "sqlite") (not .Values.sqlite.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "janus.fullname" . }}-data
  labels:
    {{- include "janus.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes: [ReadWriteOnce]
  {{- if ne .Values.sqlite.persistence.storageClass nil }}
  storageClassName: {{ .Values.sqlite.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.sqlite.persistence.size | quote }}
{{- end }}
